.SUFFIXES: .o .f90

F90    = $(FC)
FFLAGS = -g -mp
LDFLAGS = -mp

EXEC = finn_fire_emis_omp

OBJS = finn_fire_emis.o

##dependencies
#$(OBJECTS) : makefile

${EXEC} :       ${OBJS}
		${F90} -o $@ ${LDFLAGS} ${OBJS}

.f90.o:
		${F90} ${FFLAGS} -c $<

cleanup:
		rm -f ${OBJS}

clean:
		rm -f core ${EXEC} ${OBJS}
